<!--
	The sheet of paper one search result is printed on. Both public routes render
	the same document: a titled header rule, muted meta lines, optional media, a
	truncated description, and a row of pills pinned to the bottom edge.

	Every size is expressed against the sheet's own width (`cqi`), not the
	viewport, so one card reads the same whether it is a 112px thumbnail on a
	phone or the opened full-screen page. Each clamp is calibrated to hit its
	MAXIMUM at a 192px-wide sheet — the desktop card width — so desktop
	typography is unchanged by construction.
-->
<script module lang="ts">
	import type { Component } from 'svelte';

	/** One pill: a plain label, or a coloured program-area pill with its icon. */
	export interface SheetTag {
		label: string;
		/** Tailwind pill classes (e.g. `programAreaMeta(tag).pill`); grey if omitted. */
		class?: string;
		icon?: Component;
	}
</script>

<script lang="ts">
	import type { Snippet } from 'svelte';
	import { cn } from '$lib/utils';

	interface Props {
		title: string;
		/** Muted lines under the rule (event name, date, time…). Falsy entries drop out. */
		meta?: (string | null | undefined)[];
		description?: string | null;
		/** Description lines kept before truncation. */
		lines?: number;
		tags?: SheetTag[];
		/** Optional media block between the rule and the description. */
		media?: Snippet;
		/**
		 * Optional controls pinned to the top-right of the header, beside the title
		 * (a download, say). Only pass this on the OPENED page: the closed card is
		 * wrapped in a button, and nested interactive content is invalid HTML.
		 */
		actions?: Snippet;
	}

	let { title, meta = [], description, lines = 3, tags = [], media, actions }: Props = $props();

	const metaLines = $derived(meta.filter((m): m is string => !!m));
</script>

<!-- The container query element carries NO padding of its own: `cqi` resolves
     against the container's CONTENT box, so padding here would shrink the very
     unit the padding is computed from, and every clamp below would land short of
     its intended maximum. All sizing lives on the inner sheet. -->
<div class="@container h-full w-full">
	<div
		class="flex h-full flex-col overflow-hidden rounded-sm bg-white/95 p-[clamp(0.5rem,8.33cqi,1rem)] text-gray-900 shadow-xl ring-1 ring-black/5"
	>
		<div class="flex items-start justify-between gap-2 border-b border-gray-200 pb-2">
			<div class="min-w-0">
				<h2 class="line-clamp-2 text-[clamp(0.75rem,7.29cqi,0.875rem)] leading-tight font-medium">
					{title}
				</h2>
				{#each metaLines as line, i (i)}
					<p class="mt-1 text-[clamp(0.5625rem,5.42cqi,0.65rem)] text-gray-500">{line}</p>
				{/each}
			</div>
			{#if actions}
				<div class="flex shrink-0 items-center gap-1">
					{@render actions()}
				</div>
			{/if}
		</div>

		{@render media?.()}

		{#if description}
			<!-- Clamp count is data, so it rides a custom property: an interpolated
		     `line-clamp-{n}` class would never be generated by Tailwind's scanner. -->
			<p
				style="--card-lines:{lines}"
				class="mt-1.5 line-clamp-(--card-lines) text-[clamp(0.625rem,6.25cqi,0.75rem)] leading-relaxed text-gray-800"
			>
				{description}
			</p>
		{/if}

		{#if tags.length}
			<div class="mt-auto flex flex-wrap gap-1 pt-2">
				{#each tags as tag, i (i)}
					{@const Icon = tag.icon}
					<span
						class={cn(
							'inline-flex items-center gap-1 rounded-full px-1.5 py-0.5 text-[clamp(0.5625rem,5.42cqi,0.65rem)]',
							tag.class ?? 'bg-gray-100 text-gray-600'
						)}
					>
						{#if Icon}
							<Icon size="1em" weight="fill" />
						{/if}
						{tag.label}
					</span>
				{/each}
			</div>
		{/if}
	</div>
</div>
